### PR TITLE
Log iRODS errors to syslog when publishing Illumina runs

### PR DESCRIPTION
**Pull request by marcomoscasgr**
Problem: iRODS logs could not be pushed to ELK. ISG asked to have those logs available. The solution in this PR is to log errors to `syslog` so they are automatically delivered.

This branch will add/modify the following files:

Added:
- `data/config_files/log4perl_publish_illumina.conf`:  Contains the logger specifications used to log ERRORS to syslog

Changed
- `lib/npg_pipeline/function/run_data_to_irods_archiver.pm`: The command line with `npg_publish_illumina_run.pl` now accepts the option `--logconf` with the logger specification in the file above
- `lib/npg_pipeline/function/seq_to_irods_archiver.pm`: The command line with `npg_publish_illumina_run.pl` now accepts the option `--logconf` with the logger specification in the file above
- `t/20-function-run_data_to_irods_archiver.t`: Added a new test to check that the command line of `npg_publish_illumina_run.pl` with the new `--logconf` option is correct.
- `t/20-function-seq_to_irods_archiver.t`: Added the `--logconf` option to the existing test command lines.

### CODE REVIEW

**Comment by mgcam** [comment]
I wondered whether this new config file will be deployed and it seems that it will, see https://github.com/wtsi-npg/npg_seq_pipeline/blob/c74a98fd696d5063544947f964dcaf0ba6581d45/Build.PL#L10.

**Comment by marcomoscasgr** [comment]
Yes, and with this function `conf_file_path('log4perl_syslog.conf')` should be retrieved programmatically

**Comment by dkj** [comment]
Do we need to adapt `seq_to_irods_archiver` and `pp_archiver` as well?

**Comment by marcomoscasgr** [comment]
- `lib/npg_pipeline/function/seq_to_irods_archiver.pm` updated. 

- `lib/npg_pipeline/function/pp_data_to_irods_archiver.pm` should be modified in another PR since it requires some changes in `npg_publish_tree.pl` from `npg_irods` (such as adding the missing `--logconf` option in the script).

**Pull request merged**
