### PR TITLE
Add irods location loading step

### PR DESCRIPTION
**Pull request by mksanger**

### CODE REVIEW

**Comment by mksanger** [comment]
This is dependent on https://github.com/wtsi-npg/npg_seq_pipeline/pull/713, and should not be merged until it is confirmed that the JSON files are being created in the right place following a new DD containing that pr.

**Review by mgcam — APPROVED** [review]
The new feature is currently enabled for both archival and analysis pipeline. We'll run with this for now. Should not cause any problems.

**Review by mgcam — COMMENTED** [review]
No comment at this point

**Review by mgcam — CHANGES_REQUESTED** [review]
No specific changes requested at this point, just trying to withdraw the approval

**Pull request merged**
