### PR TITLE
Heron artic (full) primer version for Majora enhancement/bugfix

### PR DESCRIPTION
**Pull request by dkj**

### CODE REVIEW

**Comment by dkj** [comment]
Need change control approval before merge, else before release.

**Comment by dkj** [comment]
Improved testing would ideally be done with proper Mocking - but as we want to hand over this functionality and deprecate the code in a few months I'm loath for us to invest more time in it.

**Review by mgcam — APPROVED** [review]
The code could be improved. Considering that the responsibility for this functionality will be transferred to a different team, OK for now

**Comment by dkj** [comment]
> Need change control approval before merge, else before release.

**Comment by dkj** [comment]
https://jira.sanger.ac.uk/projects/GSU/queues/issue/GSU-367

**Pull request merged**
