### PR TITLE
delete intermediate data

### PR DESCRIPTION
**Pull request by dozy**
create list of intermediate files for later deletion in seq_alignment and add new remove_intermediate_data function to post_qc_review pipeline to actually do the deletions.

### CODE REVIEW

**Comment by mgcam** [comment]
My personal preference is not to have interdependencies between modules in npg_pipeline::function and not to have in these modules any code that is not needed for generation of the function definition.

**Comment by mp15** [comment]
The alternative could be to put the intermediate files in the no_archive directory, going to add a few tweaks to the PR but it’s nearly finished.

**Comment by dkj** [comment]
Chatted with @dozy @mgcam and @jmtcsngr : this calculation for explicit files to delete and passing that state around seems much more expensive (in complexity, and in breaking and introducing conventions) than I'd anticipated. So, having learned from this I'd recommend (simpler approach of) an intermediate files deletion pipeline function which launches a `rm -v <recal_dir>/*.cram` job which we run in the archival pipeline before `qc complete` (so avoid the directory move issue).

**Comment by dkj** [comment]
Simplified method was easier to review!
Tested on R&D run - looked good.

**Pull request merged**
